### ISSUE TITLE
Incompatibility with `javafx.beans.binding.Bindings` boolean utilities

### ISSUE THREAD

**Issue by cubuspl42** [TomasMikula/EasyBind#13]
EasyBind returns objects of generic types. JavaFX utilities like `Bindings.or` or `Bindings.not` are incompatible with `ObservableValue<Boolean>`, because their arguments are of type `ObservableBooleanValue`. I'm not sure what's the solution and/or workaround.

**Comment by ben12** [comment]
I have a workaround for that:

```java
BooleanBinding bb = Bindings.selectBoolean(EasyBind.select(control.sceneProperty())
                                                   .select(s -> s.windowProperty()) 
                                                   .selectObject(w -> w.showingProperty()));
BooleanExpression notBb = Bindings.not(bb);
```

**Comment by cubuspl42** [comment]
I had a feeling that there must be a simple wrapping utility somewhere. Still, Java's generics can be annoying.
