### ISSUE TITLE
Mapping an ObserveableMap

### ISSUE THREAD

**Issue by hrj** [TomasMikula/EasyBind#5]
I have an `ObserveableMap<K, V>`, from which I would like to create an `ObserveableList<K>` or `ObserveableList<V>`

Am I correct that this is not currently possible with EasyBind API? Would be great to have this if it isn't currently supported.

thanks for the cool library! I am using it in [this app](https://github.com/UprootLabs/unplug).
:+1:

**Comment by TomasMikula** [comment]
Hi, you are correct, this is not supported. I am trying to consolidate EasyBind and ReactFX, moving functionality to ReactFX. Thus, I am unlikely to add new features to EasyBind (I will be fixing bugs, though, when they appear). Most of EasyBind's functionality is already there in the current milestone release of ReactFX. You can always ask me how you would rewrite this or that from EasyBind to ReactFX.

This would be a good candidate for a feature request in ReactFX.

**Comment by hrj** [comment]
Oh.. that's sad to hear. My understanding is that the abstraction level was higher in EasyBind than in ReactFX. That is, in order of decreasing abstraction:

* Properties
* Events
* Listeners

EasyBind allowed working on the highest abstraction level. ReactFX would require going one level down, though it's better than listeners. Am I correct?

**Comment by TomasMikula** [comment]
You are referring to ReactFX before [Val](http://tomasmikula.github.io/blog/2015/02/10/val-a-better-observablevalue.html)s ;)
